const data = {
    model: '',
    defaultAllSize: '11',
    widthNum: '132',
    heightNum: '64',
    radius: '5',
    content: [
        {
            label: '百度',
            link: 'https://www.baidu.com',
            icon: 'https://www.baidu.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: 'Bing',
            link: 'https://www.bing.com',
            icon: 'https://cn.bing.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '抖音',
            link: 'https://www.douyin.com',
            icon: 'https://www.douyin.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '淘宝',
            link: 'https://www.taobao.com',
            icon: 'https://www.taobao.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '360',
            link: 'https://www.so.com',
            icon: 'https://www.so.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '河南交科院',
            link: 'http://39.103.131.122:8081/jkyErp/index.html#/',
            icon: 'http://39.103.131.122:8081/jkyErp/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: 'Antd',
            link: 'https://ant-design.antgroup.com/index-cn',
            icon: 'https://gw.alipayobjects.com/zos/rmsportal/rlpTLlbMzTNYuZGGCVYM.png',
            type: 'link',
            size: '11',
        }, {
            label: 'Apple',
            link: 'https://www.apple.com.cn',
            icon: 'https://www.apple.com.cn/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '吾爱破解',
            link: 'https://www.52pojie.cn/index.php',
            icon: 'https://www.52pojie.cn/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '新浪微博',
            link: 'https://www.weibo.com',
            icon: 'https://www.weibo.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '今日头条',
            link: 'https://www.toutiao.com',
            icon: 'https://www.toutiao.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: '阿里矢量图标',
            link: 'https://iconfont.cn',
            icon: 'https://img.alicdn.com/imgextra/i4/O1CN01Z5paLz1O0zuCC7osS_!!6000000001644-55-tps-83-82.svg',
            type: 'link',
            size: '11',
        }, {
            label: 'CSDN',
            link: 'https://www.csdn.com',
            icon: 'https://g.csdnimg.cn/static/logo/favicon32.ico',
            type: 'link',
            size: '11',
        }, {
            label: '爱奇艺',
            link: 'https://www.iqiyi.com',
            icon: 'https://www.iqiyi.com/favicon.ico',
            type: 'link',
            size: '11',
        }, {
            label: 'bilibili',
            link: 'https://www.bilibili.com',
            icon: 'https://www.bilibili.com/favicon.ico',
            type: 'link',
            size: '11',
        }
    ]
}

export default data;