const funtabsData = {
	model: "",
	widthNum: 160,
	heightNum: 64,
	gridWidthNum: 1314,
	radius: 12,
	gap: 24,
	cardStyle: "defaultCard",
	tabsActiveKey: 0,
	backgroundImage: "/images/wallpaper.JPG",
	content: [
		{
			label: "首页",
			key: 0,
			content: [
				{
					label: "便捷记事本",
					type: "note",
					link: null,
					size: null,
					x: "80",
					y: "20",
					icon: null,
					backgroundColor: null,
					id: 0,
				},
				{
					label: "实时热榜",
					type: "hotEventList",
					link: null,
					size: null,
					x: null,
					y: null,
					icon: null,
					backgroundColor: null,
					id: 1,
				},
				{
					label: "实时天气",
					type: "localWeather",
					link: null,
					size: null,
					x: null,
					y: null,
					icon: null,
					backgroundColor: null,
					id: 2,
				},
				{
					label: "雨云-高性价比服务器",
					type: "link",
					link: "https://www.rainyun.com/funtabs_",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://app.rainyun.com/favicon.ico",
					backgroundColor: null,
					id: 3,
				},
				{
					label: "阿里云",
					type: "link",
					link: "https://aliyun.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/aliyun.svg",
					backgroundColor: "#FF6900",
					id: 4,
				},
				{
					label: "微博",
					type: "link",
					link: "https://weibo.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/weibo.svg",
					backgroundColor: "#ffffff",
					id: 6,
				},
				{
					label: "抖音",
					type: "link",
					link: "https://douyin.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/douyin.svg",
					backgroundColor: "#000000",
					id: 7,
				},
				{
					label: "爱奇艺",
					type: "link",
					link: "https://iqiyi.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/iqiyi.svg",
					backgroundColor: "#00cc4c",
					id: 8,
				},
				{
					label: "腾讯视频",
					type: "link",
					link: "https://v.qq.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/qqvideo.svg",
					backgroundColor: null,
					id: 9,
				},
				{
					label: "优酷",
					type: "link",
					link: "https://youku.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/youku.svg",
					backgroundColor: null,
					id: 10,
				},
				{
					label: "趣标签页官网",
					type: "link",
					link: "https://www.funtabs.cn",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://funtabs.cn/logo.svg",
					backgroundColor: null,
					id: 11,
				},
				{
					label: "京东",
					type: "link",
					link: "https://jd.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/jd.svg",
					backgroundColor: "#CB0507",
					id: 17,
				},
			],
		},
		{
			label: "设计灵感",
			key: 1,
			content: [
				{
					label: "阿里矢量图库",
					type: "link",
					link: "https://iconfont.cn",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://img.alicdn.com/imgextra/i4/O1CN01Z5paLz1O0zuCC7osS_!!6000000001644-55-tps-83-82.svg",
					backgroundColor: null,
					id: 12,
				},
				{
					label: "Sketch素材",
					type: "link",
					link: "https://oursketch.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/sketch.svg",
					backgroundColor: null,
					id: 13,
				},
				{
					label: "app应用设计示例",
					type: "link",
					link: "https://screenlane.com/",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/screenlane.svg",
					backgroundColor: null,
					id: 14,
				},
				{
					label: "imgTools",
					type: "link",
					link: "https://imagestool.com/zh_CN/",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/img.svg",
					backgroundColor: null,
					id: 15,
				},
				{
					label: "在线抠图",
					type: "link",
					link: "https://www.remove.bg/zh",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/removeBg.svg",
					backgroundColor: null,
					id: 16,
				},
			],
		},
		{
			label: "程序代码",
			key: 2,
			content: [
				{
					label: "Github",
					type: "link",
					link: "https://github.com",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/github.svg",
					backgroundColor: null,
					id: 18,
				},
				{
					label: "CSDN",
					type: "link",
					link: "https://csdn.net",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/csdn.svg",
					backgroundColor: "#fc5734",
					id: 19,
				},
				{
					label: "稀土掘金",
					type: "link",
					link: "https://juejin.cn",
					size: 11,
					x: "80",
					y: "20",
					icon: "https://oss.funtabs.cn/icon/juejin.svg",
					backgroundColor: "#2080ff",
					id: 20,
				},
			],
		},
	],
};

export { funtabsData };
